version: '3.8'

services:
  rawg-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RawgApi__ApiKey=${RAWG_API_KEY}
      - ApiKey__RequireApiKey=${REQUIRE_API_KEY:-false}
      - ApiKey__ValidApiKeys__0=${API_KEY_1}
      - ApiKey__ValidApiKeys__1=${API_KEY_2}
      - Cors__Enabled=${CORS_ENABLED:-true}
      - Cors__AllowedOrigins__0=${CORS_ORIGIN_1:-http://localhost:3000}
      - Cors__AllowedOrigins__1=${CORS_ORIGIN_2:-https://localhost:3000}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/status/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
