name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
      
    - name: Pack (for validation)
      run: |
        dotnet pack src/RawgApi.Models/RawgApi.Models.csproj --configuration Release --output nupkgs --no-build
        dotnet pack src/RawgApi.Client/RawgApi.Client.csproj --configuration Release --output nupkgs --no-build 